(function(g){var window=this;var qBa=function(a,b){return g.Vb(a,b)},Q6=function(a){g.Fm(a,"zx",g.zb());
return a},R6=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.Im(a.g,b,c)},rBa=function(a,b){var c=[];
g.rk(b,function(a){try{var b=g.eD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.dD(b)&&c.push(a):c.push(a)},a);
return c},sBa=function(a,b){var c=rBa(a,b);
(0,g.B)(c,function(a){g.eD.prototype.remove.call(this,a)},a)},tBa=function(a){if(a.zd){if(a.zd.locationOverrideToken)return{locationOverrideToken:a.zd.locationOverrideToken};
if(null!=a.zd.latitudeE7&&null!=a.zd.longitudeE7)return{latitudeE7:a.zd.latitudeE7,longitudeE7:a.zd.longitudeE7}}return null},uBa=function(a,b,c,d){var e=new g.wm(null,void 0);
a&&g.xm(e,a);b&&g.ym(e,b);c&&g.zm(e,c);d&&g.Am(e,d);return e},vBa=function(a){g.UF[a]&&(a=g.UF[a],(0,g.B)(a,function(a){g.SF[a]&&delete g.SF[a]}),a.length=0)},wBa=function(a){var b=g.RF();
if(b)if(b.clear(a),a)vBa(a);else for(var c in g.UF)vBa(c)},S6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.qm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",xBa(this,a.capabilities||""),yBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},xBa=function(a,b){a.capabilities.clear();
(0,g.Ld)(b.split(","),g.Ga(qBa,zBa)).forEach(function(b){a.capabilities.add(b)})},yBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},T6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},U6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},ABa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},BBa=function(a){return new T6(a)},CBa=function(a){return g.Aa(a)?(0,g.G)(a,BBa):[]},V6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},W6=function(a){return g.Aa(a)?"["+(0,g.G)(a,V6).join(",")+"]":"null"},X6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},DBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},Y6=function(a,b){return g.Ma(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},Z6=function(a,b){return g.Ma(a,function(a){return U6(a,b)})},EBa=function(){var a=(0,g.QG)();
a&&sBa(a,a.g.Vd(!0))},$6=function(){var a=g.TG("yt-remote-connected-devices")||[];
g.ib(a);return a},FBa=function(a){if(g.Ra(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},GBa=function(a){g.SG("yt-remote-connected-devices",a,86400)},b7=function(){if(a7)return a7;
var a=g.TG("yt-remote-device-id");a||(a=X6(),g.SG("yt-remote-device-id",a,31536E3));for(var b=$6(),c=1,d=a;g.Qa(b,d);)c++,d=a+"#"+c;return a7=d},c7=function(){var a=$6(),b=b7();
g.Qa(a,b);g.VG()&&g.kb(a,b);a=FBa(a);if(g.Ra(a))try{g.CG("remote_sid")}catch(c){}else try{g.BG("remote_sid",a.join(","),-1)}catch(c){}},HBa=function(){return g.TG("yt-remote-session-browser-channel")},IBa=function(){return g.TG("yt-remote-local-screens")||[]},JBa=function(){g.SG("yt-remote-lounge-token-expiration",!0,86400)},KBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(IBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.em)(c,function(a){return!g.Qa(b,a)})&&JBa();
g.SG("yt-remote-local-screens",a,31536E3)},LBa=function(a,b){g.SG("yt-remote-session-browser-channel",a);
g.SG("yt-remote-session-screen-id",b);var c=$6(),d=b7();g.Qa(c,d)||c.push(d);GBa(c);c7()},d7=function(a){a||(g.UG("yt-remote-session-screen-id"),g.UG("yt-remote-session-video-id"));
c7();a=$6();g.Va(a,b7());GBa(a)},MBa=function(){if(!e7){var a=g.pD();
a&&(e7=new g.ZC(a))}return e7?!!e7.get("yt-remote-use-staging-server"):!1},NBa=function(){var a=window.document.createElement("a");
g.ad(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Db(a)},OBa=function(a,b){var c=g.Ed("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.bd(c,g.ce("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},PBa=function(){var a=NBa(),b=window.document.getElementById(a),c=b&&g.cF(b,"loaded");
c||b&&!c||(b=OBa(a,function(){g.cF(b,"loaded")||(g.bF(b,"loaded","true"),g.YF(a),g.YD(g.Ga(wBa,a),0))}))},f7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},QBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},g7=function(a){a.length?RBa(a.shift(),function(){g7(a)}):h7()},SBa=function(a){return"chrome-extension://"+a+i7},RBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},j7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},h7=function(){var a=QBa();
a&&a(!1,"No cast extension found")},k7=function(){if(TBa){var a=2,b=QBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;RBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",h7,c)}},UBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(k7(),a({command:"cast.sender.init"}))},VBa=function(){k7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);g7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+i7,"//www.gstatic.com/eureka/clank"+i7])},l7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.qd=b;this.B=(0,g.z)(this.aK,this);this.g=!1;this.l=0;this.o=this.Ca=null;this.A=[]},m7=function(){},n7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Mm(this);this.l=new g.sg;this.l.setInterval(250)},XBa=function(a,b,c){a.Lj=1;
a.mh=Q6(b.clone());a.Ti=c;a.B=!0;WBa(a,null)},o7=function(a,b,c,d,e){a.Lj=1;
a.mh=Q6(b.clone());a.Ti=null;a.B=c;e&&(a.hE=!1);WBa(a,d)},WBa=function(a,b){a.Ck=(0,g.F)();
p7(a);a.Jh=a.mh.clone();R6(a.Jh,"t",a.C);a.Tm=0;a.Qc=a.g.Mr(a.g.Jm()?b:null);0<a.Bs&&(a.Rp=new g.Vk((0,g.z)(a.zF,a,a.Qc),a.Bs));a.W.U(a.Qc,"readystatechange",a.xV);var c=a.oi?g.cc(a.oi):{};a.Ti?(a.Gq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Jh,a.Gq,a.Ti,c)):(a.Gq="GET",a.hE&&!g.Ad&&(c.Connection="close"),a.Qc.send(a.Jh,a.Gq,null,c));a.g.yf(1)},$Ba=function(a,b,c){for(var d=!0;!a.Yh&&a.Tm<c.length;){var e=YBa(a,c);
if(e==q7){4==b&&(a.nh=4,r7(15),d=!1);break}else if(e==ZBa){a.nh=4;r7(16);d=!1;break}else s7(a,e)}4==b&&0==c.length&&(a.nh=1,r7(17),d=!1);a.Ef=a.Ef&&d;d||(t7(a),u7(a))},YBa=function(a,b){var c=a.Tm,d=b.indexOf("\n",c);
if(-1==d)return q7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return ZBa;d+=1;if(d+c>b.length)return q7;var e=b.substr(d,c);a.Tm=d+c;return e},bCa=function(a,b){a.Ck=(0,g.F)();
p7(a);var c=b?window.location.hostname:"";a.Jh=a.mh.clone();g.Fm(a.Jh,"DOMAIN",c);g.Fm(a.Jh,"t",a.C);try{a.Ff=new window.ActiveXObject("htmlfile")}catch(n){t7(a);a.nh=7;r7(22);u7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in v7)k=v7[l];else if(l in aCa)k=v7[l]=aCa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=v7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.cd(g.yc("b/12014412"),d);a.Ff.open();a.Ff.write(g.Vc(c));a.Ff.close();a.Ff.parentWindow.m=(0,g.z)(a.GU,a);a.Ff.parentWindow.d=(0,g.z)(a.qD,a,!0);a.Ff.parentWindow.rpcClose=(0,g.z)(a.qD,a,!1);c=a.Ff.createElement("DIV");a.Ff.parentWindow.document.body.appendChild(c);d=g.Mc(a.Jh.toString());d=g.sb(g.Jc(d));d=g.cd(g.yc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Vc(d);
a.g.yf(1)},p7=function(a){a.dw=(0,g.F)()+a.A;
cCa(a,a.A)},cCa=function(a,b){if(null!=a.Sk)throw Error("WatchDog timer not null");
a.Sk=w7((0,g.z)(a.WU,a),b)},x7=function(a){a.Sk&&(g.w.clearTimeout(a.Sk),a.Sk=null)},u7=function(a){a.g.yz()||a.Yh||a.g.Dp(a)},t7=function(a){x7(a);
g.$e(a.Rp);a.Rp=null;a.l.stop();g.Sm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Ff&&(a.Ff=null)},s7=function(a,b){try{a.g.jD(a,b),a.g.yf(4)}catch(c){}},eCa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;dCa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){eCa(a,b,c,d,f)},f)})}},dCa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{y7(d),c(!0)}catch(e){}};
d.onerror=function(){try{y7(d),c(!1)}catch(e){}};
d.onabort=function(){try{y7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{y7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},y7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},fCa=function(a){this.g=a;
this.l=new m7},gCa=function(a){var b=z7(a.g,a.al,"/mail/images/cleardot.gif");
Q6(b);eCa(b.toString(),5E3,(0,g.z)(a.mJ,a),3,2E3);a.yf(1)},B7=function(a){var b=a.g.H;
if(null!=b)r7(5),b?(r7(11),A7(a.g,a,!1)):(r7(12),A7(a.g,a,!0));else if(a.we=new n7(a,void 0,void 0,void 0),a.we.oi=a.zs,b=a.g,b=z7(b,b.Jm()?a.Fl:null,a.As),r7(5),!g.yd||g.uc(10))R6(b,"TYPE","xmlhttp"),o7(a.we,b,!1,a.Fl,!1);else{R6(b,"TYPE","html");var c=a.we;a=!!a.Fl;c.Lj=3;c.mh=Q6(b.clone());bCa(c,a)}},C7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new m7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},hCa=function(a,b){this.g=a;
this.map=b;this.context=null},iCa=function(a){g.bf.call(this,"statevent",a)},jCa=function(a,b){g.bf.call(this,"timingevent",a);
this.size=b},kCa=function(a){g.bf.call(this,"serverreachability",a)},nCa=function(a){lCa(a);
if(3==a.g){var b=a.rm++,c=a.mo.clone();g.Fm(c,"SID",a.o);g.Fm(c,"RID",b);g.Fm(c,"TYPE","terminate");D7(a,c);b=new n7(a,a.o,b,void 0);b.Lj=2;b.mh=Q6(c.clone());(new window.Image).src=b.mh;b.Ck=(0,g.F)();p7(b)}mCa(a)},oCa=function(a){a.HJ(1,0);
a.mo=z7(a,null,a.ys);E7(a)},lCa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.sg&&(g.w.clearTimeout(a.sg),a.sg=null);F7(a);a.be&&(a.be.cancel(),a.be=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},pCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new hCa(a.sQ++,b));2!=a.g&&3!=a.g||E7(a)},E7=function(a){a.be||a.eh||(a.eh=w7((0,g.z)(a.oD,a),0),a.Aj=0)},rCa=function(a,b){if(1==a.g){if(!b){a.rm=Math.floor(1E5*Math.random());
var c=a.rm++,d=new n7(a,"",c,void 0);d.oi=null;var e=G7(a),f=a.mo.clone();g.Fm(f,"RID",c);g.Fm(f,"CVER","1");D7(a,f);XBa(d,f,e);a.be=d;a.g=2}}else 3==a.g&&(b?qCa(a,b):0==a.l.length||a.be||qCa(a))},qCa=function(a,b){if(b)if(6<a.bi){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.rm-1;var d=G7(a)}else c=b.D,d=b.Ti;else c=a.rm++,d=G7(a);var e=a.mo.clone();g.Fm(e,"SID",a.o);g.Fm(e,"RID",c);g.Fm(e,"AID",a.Zj);D7(a,e);c=new n7(a,a.o,c,a.Aj+1);c.oi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.be=c;XBa(c,e,d)},D7=function(a,b){if(a.pd){var c=a.pd.ez();
c&&g.Lb(c,function(a,c){g.Fm(b,c,a)})}},G7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.bi&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.bi?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},sCa=function(a){a.tc||a.sg||(a.D=1,a.sg=w7((0,g.z)(a.nD,a),0),a.nj=0)},H7=function(a){if(a.tc||a.sg||3<=a.nj)return!1;
a.D++;a.sg=w7((0,g.z)(a.nD,a),tCa(a,a.nj));a.nj++;return!0},A7=function(a,b,c){a.Fq=c;
a.Tf=b.Dg;a.C||oCa(a)},F7=function(a){null!=a.di&&(g.w.clearTimeout(a.di),a.di=null)},tCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},I7=function(a,b){if(2==b||9==b){var c=null;
a.pd&&(c=null);var d=(0,g.z)(a.rW,a);c||(c=new g.wm("//www.google.com/images/cleardot.gif"),Q6(c));dCa(c.toString(),1E4,d)}else r7(2);uCa(a,b)},uCa=function(a,b){a.g=0;
a.pd&&a.pd.Ux(b);mCa(a);lCa(a)},mCa=function(a){a.g=0;
a.Tf=-1;if(a.pd)if(0==a.A.length&&0==a.l.length)a.pd.yr();else{g.Ya(a.A);var b=g.Ya(a.l);a.A.length=0;a.l.length=0;a.pd.yr(b)}},z7=function(a,b,c){var d=g.Gm(c);
if(""!=d.l)b&&g.ym(d,b+"."+d.l),g.zm(d,d.B);else{var e=window.location;d=uBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.rl&&g.Lb(a.rl,function(a,b){g.Fm(d,b,a)});
g.Fm(d,"VER",a.bi);D7(a,d);return d},w7=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},r7=function(a){J7.dispatchEvent(new iCa(J7,a))},vCa=function(){},wCa=function(a,b){this.action=a;
this.params=b||{}},K7=function(a,b){g.M.call(this);
this.g=new g.Yt(this.xU,0,this);g.N(this,this.g);this.qd=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},L7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.YC;this.l=new K7(this.cX,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},xCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Fq,sessionId:a.g.o,arrayId:a.g.Zj}},yCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&rCa(a.g),nCa(a.g));a.F=0},M7=function(a){return!!a.g&&3==a.g.g},zCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},N7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ig(a)||"";b&&(this.port=":"+b);this.domain=g.Hg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cb(a,"10.0")&&(this.l=!1))},O7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Rg(c+b,{})},P7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ga(a.A,d,!0),onError:g.Ga(a.o,e),wd:g.Ga(a.B,e)};c&&(a.Nb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oE(b,a)},DCa=function(){var a=ACa;
BCa();Q7.push(a);CCa(Q7)},R7=function(a,b){BCa();
var c=Q7,d=ECa(a,String(b));g.Ra(c)?FCa(d):(CCa(c),(0,g.B)(c,function(a){a(d)}))},BCa=function(){Q7||(Q7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",Q7,void 0))},FCa=function(a){var b=(S7+1)%50;
S7=b;T7[b]=a;U7||(U7=49==b)},CCa=function(a){var b=T7;
if(b[0]){var c=S7,d=U7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
T7=Array(50);S7=-1;U7=!1}},ECa=function(a,b){var c=((0,g.F)()-GCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},V7=function(a){g.JF.call(this);
this.D=a;this.g=[]},HCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},ICa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Ld)(a.g,function(a){return!!Y6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=HCa(a,b[d])||c;return c},JCa=function(a,b){var c=a.g.length;
a.g=(0,g.Ld)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},W7=function(a,b,c,d){g.JF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ca=window.NaN},Y7=function(a){V7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;X7(this);this.info("Initializing with "+W6(this.g))},KCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=O7(a.o,"/pairing/get_lounge_token_batch");
P7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.nK,a),(0,g.z)(a.mK,a))}},X7=function(a){var b=CBa(IBa());
b=(0,g.Ld)(b,function(a){return!a.uuid});
return ICa(a,b)},Z7=function(a,b){KBa((0,g.G)(a.g,ABa));
b&&JBa()},a8=function(a,b){g.JF.call(this);
this.C=b;var c=g.TG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Qa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;$7("Initialized with "+g.zg(this.g))},LCa=function(a,b,c){var d=O7(a.B,"/pairing/get_screen_availability");
P7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},b8=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||($7("Updated online screens: "+g.zg(a.g)),a.g=b,a.R("screenChange"));MCa(a)},c8=function(a){(0,window.isNaN)(a.o)||g.$D(a.o);
a.o=g.YD((0,g.z)(a.tv,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},$7=function(a){R7("OnlineScreenService",a)},NCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},MCa=function(a){a=g.Sb(g.Mb(a.g,function(a){return a}));
g.ib(a);a.length?g.SG("yt-remote-online-screen-ids",a.join(","),60):g.UG("yt-remote-online-screen-ids")},d8=function(a){V7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};OCa(this)},QCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.oe();if(k=(c?Z6(k,c):null)||Z6(k,b)){k.uuid=b;var l=e8(a,k);LCa(a.l,l,function(a){e(a?l:null)})}else c?PCa(a,c,(0,g.z)(function(a){var f=e8(this,new T6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));LCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},RCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},PCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Nb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oE(O7(a.C,"/pairing/get_lounge_token_batch"),e)},SCa=function(a){a.g=a.o.oe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+W6(a.g))},OCa=function(a){f8(a);
a.o=new Y7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.CK,a));SCa(a);a.A=CBa(g.TG("yt-remote-automatic-screen-cache")||[]);f8(a);a.info("Initializing automatic screens: "+W6(a.A));a.l=new a8(a.C,(0,g.z)(a.oe,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},e8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=Z6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.SG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,ABa)));f8(a);a.B[b.uuid]=b.id;g.SG("yt-remote-device-id-map",a.B,31536E3);return b},f8=function(a){a.B=g.TG("yt-remote-device-id-map")||{}},g8=function(a,b,c){g.JF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},h8=function(a,b){R7(a.K,b)},i8=function(a,b){g8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.iX,this);this.B=(0,g.z)(this.iV,this);this.A=g.YD((0,g.z)(function(){TCa(this,null)},this),12E4)},UCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.zg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){h8(this,"Failed to send message: getMdxSessionStatus.")},a)):h8(a,"Sending yt message without session: "+g.zg(b))},TCa=function(a,b){g.$D(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Ep,a),d=(0,g.z)(a.te,a);a.oz(b,c,d,5)}}else a.te(Error("Waiting for session status timed out."))},j8=function(a,b,c){g8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.lX,this);this.g=g.y},VCa=function(a){a.g=a.H.GF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Ep(a)},a),(0,g.z)(function(a){this.g=g.y;
this.te(a)},a))},WCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}MBa()&&(b.env_useStageMdx=1);return g.Pg(b)},k8=function(a,b){g8.call(this,a,b,"ManualSession");
this.g=g.YD((0,g.z)(this.bk,this,null),150)},l8=function(a,b,c,d){g.JF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.GT,this)},XCa=function(a,b){return b?g.Ma(a.o,function(a){return U6(b,a.label)},a):null},m8=function(a){R7("Controller",a)},ACa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},n8=function(a){return a.B||!!a.o.length||!!a.g},o8=function(a,b,c){b!=a.g&&(g.$e(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.lD,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.bk(null)):a.R("yt-remote-cast2-session-change",null))},YCa=function(a){var b=a.l.FF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&U6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=XCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},dDa=function(a,b,c,d,e,f,k){ZCa()?$Ca(b,e,f,k)&&(q8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?aDa(a,c):(window.__onGCastApiAvailable=function(b,d){b?aDa(a,c):(r8("Failed to load cast API: "+d),s8(!1),q8(!1),g.UG("yt-remote-cast-available"),g.UG("yt-remote-cast-receiver"),bDa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):PBa():j7("CriOS")?UBa():j7("Android")&&j7("Chrome/")&&window.navigator.presentation?VBa():window.chrome&&window.navigator.presentation&&!j7("Edge")?(k7(),g7(cDa.map(SBa))):h7())):p8("Cannot initialize because not running Chrome")},bDa=function(){p8("dispose");
var a=t8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);eDa(!1);g.WF(u8);u8.length=0},v8=function(){return!!g.TG("yt-remote-cast-installed")},fDa=function(){var a=g.TG("yt-remote-cast-receiver");
return a?a.friendlyName:null},gDa=function(){p8("clearCurrentReceiver");
g.UG("yt-remote-cast-receiver")},hDa=function(){return v8()?t8()?t8().getCastSession():(r8("getCastSelector: Cast is not initialized."),null):(r8("getCastSelector: Cast API is not installed!"),null)},x8=function(){v8()?t8()?w8()?(p8("Requesting cast selector."),t8().requestSession()):(p8("Wait for cast API to be ready to request the session."),u8.push(g.VF("yt-remote-cast2-api-ready",x8))):r8("requestCastSelector: Cast is not initialized."):r8("requestCastSelector: Cast API is not installed!")},y8=
function(a,b){w8()?t8().setConnectedScreenStatus(a,b):r8("setConnectedScreenStatus called before ready.")},ZCa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.FI||a},iDa=function(a,b){t8().init(a,b)},$Ca=function(a,b,c,d){var e=!1;
t8()||(a=new l8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.SG("yt-remote-cast-available",a);g.ZF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){p8("onReceiverSelected: "+a.friendlyName);
g.SG("yt-remote-cast-receiver",a);g.ZF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){p8("onReceiverResumed: "+a.friendlyName);
g.SG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){p8("onSessionChange: "+V6(a));
a||g.UG("yt-remote-cast-receiver");g.ZF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
p8("cloudview.createSingleton_: "+e);return e},t8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},aDa=function(a,b){s8(!0);
q8(!1);iDa(a,function(a){a?(eDa(!0),g.YF("yt-remote-cast2-api-ready")):(r8("Failed to initialize cast API."),s8(!1),g.UG("yt-remote-cast-available"),g.UG("yt-remote-cast-receiver"),bDa());b(a)})},p8=function(a){R7("cloudview",a)},r8=function(a){R7("cloudview",a)},s8=function(a){p8("setCastInstalled_ "+a);
g.SG("yt-remote-cast-installed",a)},w8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},eDa=function(a){p8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},q8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},z8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Wf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},A8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Wf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},B8=function(a){return a.ob()?((0,g.F)()-a.D)/1E3:0},C8=function(a,b){a.F=b;
a.D=(0,g.F)()},D8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},E8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&A8(a)},F8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.l);b.hasPrevious=a.Wf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},H8=function(a,b){g.JF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.oC;this.o=this.l=null;this.H=(0,g.z)(this.cR,this);this.D=(0,g.z)(this.wm,this);this.F=(0,g.z)(this.bR,this);this.I=(0,g.z)(this.oR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lw,this),jDa(this))):c=3;0!=c&&(b?this.lw(c):g.YD((0,g.z)(function(){this.lw(c)},this),0));
var d=hDa();d&&G8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},I8=function(a){return new z8(a.A.getPlayerContextData())},jDa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ga(this.BT,a),this))},a)},kDa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},J8=function(a,b){50>a.B.Dc()&&g.qC(a.B,b)},L8=function(a,b,c){var d=I8(a);
C8(d,c);-1E3!=d.g&&(d.g=b);K8(a,d)},M8=function(a,b,c){a.A.sendMessage(b,c)},K8=function(a,b){kDa(a);
a.A.setPlayerContextData(F8(b));jDa(a)},G8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.wm(null));
a.o=b;a.o&&(R7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.wm(a.o.media[0]))},lDa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=I8(a);b.contentId!=d.videoId&&R7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;C8(d,a.l.getEstimatedTime());K8(a,d)}else R7("CP","No cast media video. Ignoring state update.")},N8=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),M8(this,b,c))},a)},O8=function(a,b,c){g.JF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.T=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.T.push(g.sF(window,"beforeunload",(0,g.z)(this.eK,this)));this.l=[];this.Za=new z8;this.Z=b.id;this.g=mDa(this,c);this.g.subscribe("handlerOpened",this.gR,this);this.g.subscribe("handlerClosed",this.dR,this);this.g.subscribe("handlerError",this.eR,this);this.g.subscribe("handlerMessage",this.fR,this);zCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.VG()&&g.SG("yt-remote-session-video-id",a)},this)},P8=function(a){R7("conn",a)},mDa=function(a,b){return new L7(O7(a.ra,"/bc"),b)},Q8=function(a,b){a.R("proxyStateChange",b)},nDa=function(a){a.B=g.YD((0,g.z)(function(){P8("Connecting timeout");
this.C(1)},a),2E4)},R8=function(a){g.$D(a.B);
a.B=window.NaN},S8=function(a){g.$D(a.K);
a.K=window.NaN},oDa=function(a){T8(a);
a.J=g.YD((0,g.z)(function(){U8(this,"getNowPlaying")},a),2E4)},T8=function(a){g.$D(a.J);
a.J=window.NaN},qDa=function(a,b){b&&(R8(a),S8(a));
b==(M7(a.g)&&(0,window.isNaN)(a.B))?b&&(Q8(a,1),U8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),Q8(a,1),U8(a,"getNowPlaying"),pDa(a)):a.C(1)},rDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Yb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},sDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;E8(a.Za,c,d);a.R("remoteQueueChange")},uDa=function(a,b){b.params=b.params||{};
sDa(a,b);tDa(a,b);a.R("autoplayDismissed")},tDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
C8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?oDa(a):T8(a);
a.R("remotePlayerChange")},vDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);C8(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},wDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},xDa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},yDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Wf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},pDa=function(a){g.$D(a.I);
a.I=g.YD((0,g.z)(a.C,a,1),864E5)},U8=function(a,b,c){c?P8("Sending: action="+b+", params="+g.zg(c)):P8("Sending: action="+b);
a.g.sendMessage(b,c)},V8=function(a){V7.call(this,"ScreenServiceProxy");
this.gd=a;this.l=[];this.l.push(this.gd.$_s("screenChange",(0,g.z)(this.gX,this)));this.l.push(this.gd.$_s("onlineScreenChange",(0,g.z)(this.dT,this)))},DDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.SD("MDX_CONFIG")||b;EBa();c7();W8||(W8=new N7(b?b.loungeApiHost:void 0),MBa()&&(W8.g="/api/loungedev"));X8||(X8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",X8,void 0));zDa();var c=Y8();if(!c){var d=new d8(W8);g.va("yt.mdx.remote.screenService_",d,void 0);c=Y8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);dDa(a,d,function(a){a?Z8()&&y8(Z8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ZF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),$8("Initializing: "+g.zg(b)),a9.push(g.VF("yt-remote-cast2-availability-change",function(){g.ZF("yt-remote-receiver-availability-change")})),a9.push(g.VF("yt-remote-cast2-receiver-selected",function(){b9(null);
g.ZF("yt-remote-auto-connect","cast-selector-receiver")})),a9.push(g.VF("yt-remote-cast2-receiver-resumed",function(){g.ZF("yt-remote-receiver-resumed","cast-selector-receiver")})),a9.push(g.VF("yt-remote-cast2-session-change",ADa)),a9.push(g.VF("yt-remote-connection-change",function(a){a?y8(Z8(),"YouTube TV"):c9()||(y8(null,null),gDa())})),a=d9(),b.isAuto&&(a.id+="#dial"),g.PF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),$8(" -- with channel params: "+
g.zg(a)),BDa(a),c.start(),Z8()||CDa())},FDa=function(){var a=EDa();
v8()&&g.TG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},EDa=function(){var a=Y8().gd.$_gos();
var b=e9();b&&f9()&&(Y6(a,b)||a.push(b));return DBa(a)},g9=function(){var a=GDa();
!a&&v8()&&fDa()&&(a={key:"cast-selector-receiver",name:fDa()});return a},GDa=function(){var a=EDa(),b=e9();
b||(b=c9());return g.Ma(a,function(a){return b&&U6(b,a.key)?!0:!1})},e9=function(){var a=Z8();
if(!a)return null;var b=Y8().oe();return Z6(b,a)},ADa=function(a){$8("remote.onCastSessionChange_: "+V6(a));
if(a){var b=e9();b&&b.id==a.id?y8(b.id,"YouTube TV"):(b&&h9(),i9(a,1))}else f9()&&h9()},h9=function(){w8()?t8().stopSession():r8("stopSession called before API ready.");
var a=f9();a&&(a.disconnect(1),j9(null))},k9=function(){var a=f9();
return!!a&&3!=a.getProxyState()},$8=function(a){R7("remote",a)},Y8=function(){if(!l9){var a=g.x("yt.mdx.remote.screenService_");
l9=a?new V8(a):null}return l9},Z8=function(){return g.x("yt.mdx.remote.currentScreenId_")},HDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},IDa=function(){return g.x("yt.mdx.remote.connectData_")},b9=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},f9=function(){return g.x("yt.mdx.remote.connection_")},j9=function(a){var b=f9();
b9(null);a||HDa("");g.va("yt.mdx.remote.connection_",a,void 0);X8&&((0,g.B)(X8,function(b){b(a)}),X8.length=0);
b&&!a?g.ZF("yt-remote-connection-change",!1):!b&&a&&g.ZF("yt-remote-connection-change",!0)},c9=function(){var a=g.VG();
if(!a)return null;var b=Y8().oe();return Z6(b,a)},i9=function(a,b){e9()&&e9();
HDa(a.id);var c=new O8(W8,a,d9());c.connect(b,IDa());c.subscribe("beforeDisconnect",function(a){g.ZF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){f9()&&j9(null)});
j9(c)},CDa=function(){var a=c9();
a?($8("Resume connection to: "+V6(a)),i9(a,0)):(d7(),gDa(),$8("Skipping connecting because no session screen found."))},zDa=function(){var a=d9();
if(g.Yb(a)){a=b7();var b=g.TG("yt-remote-session-name")||"",c=g.TG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},d9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},BDa=function(a){a?(g.SG("yt-remote-session-app",a.app),g.SG("yt-remote-session-name",a.name)):(g.UG("yt-remote-session-app"),g.UG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},m9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.GF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.vS);this.o.O(b,"captionschanged",this.aR);this.o.O(b,"captionssettingschanged",this.TE);this.o.O(b,"videoplayerreset",this.Fp);this.o.O(b,"mdxautoplaycancel",this.lJ);this.T=this.o.O(b,"onVolumeChange",this.VC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.iD,this);c.subscribe("remotePlayerChange",this.zm,this);c.subscribe("remoteQueueChange",this.Fp,this);c.subscribe("autoplayUpNext",this.GC,
this);c.subscribe("previousNextChange",this.fD,this);c.subscribe("nowAutoplaying",this.XC,this);c.subscribe("autoplayDismissed",this.FC,this);this.suggestion=null;this.H=new g.vP(64);this.A=new g.Yt(this.PE,500,this);g.N(this,this.A);this.B=new g.Yt(this.QE,1E3,this);g.N(this,this.B);this.J=new l7(this.HW,0,this);g.N(this,this.J);this.C={};this.K=new g.Yt(this.pF,1E3,this);g.N(this,this.K);this.I=new g.Vk(this.ZO,1E3,this);g.N(this,this.I);this.M=g.y;this.TE();this.Fp();this.zm()},n9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},JDa=function(a){n9(a,0);
a.A.stop();o9(a,new g.vP(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Li()},g.fc(c,b));a.g.CE(a.l.getVideoData(1).videoId,c);a.C=I8(a.g).l}},r9=function(a,b){var c=a.l.eg();
if(c){var d=c.ke();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Uj;f=tBa(f);var n=I8(c);l=l||0;var p={videoId:k,currentIndex:l};E8(n,k,l);g.t(b)&&(C8(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.zg(f));M8(c,"setPlaylist",p);e||K8(c,n);o9(a,new g.vP(1))},KDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{iA:1});
c&&c.length?(a.l.Od("captions","track",b),a.D=!1):(a.l.kk("captions"),a.D=!0)}else a.l.Od("captions","track",{})},p9=function(a){return I8(a.g).videoId==a.l.getVideoData(1).videoId},o9=function(a,b){a.B.stop();
var c=a.H;if(!g.AP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.SU(a.l,d);a.H=b;LDa(a.F,c,b)}},s9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.lpa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.l=new g.IV(this,250);g.N(this,this.l);this.A=a;this.O(a,"presentingplayerstatechange",this.B);MDa(this,g.PU(a))},MDa=function(a,b){if(3==a.A.Oa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.M0("Error on $RECEIVER_NAME",c):b.ob()||g.X(b,4)?g.M0("Playing on $RECEIVER_NAME",c):g.M0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.SZ.call(this,"Play on",0,a,b);
this.l=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},u9=function(a){g.oV.call(this,a);
this.o={key:X6(),name:"This computer"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.vP(64);this.H=0;if(!g.YM(g.Y(this.g))){a=this.g;var b=g.KH(a);b&&(b=b.bp())&&(b=new t9(a,b),g.N(this,b));b=new s9(a);g.N(this,b);g.hV(a,b.element,4)}},LDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.FP(c,b))},v9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)h9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.eg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Uj,index:Math.max(a.g.mB(),0),currentTime:0==f?void 0:f};(d=tBa(d))&&(c.locationInfo=d);d=c}else d=null;$8("Connecting to: "+g.zg(b));"cast-selector-receiver"==b.key?(b9(d||null),w8()?t8().setLaunchParams(d||null):
r8("setLaunchParams called before ready.")):!d&&k9()&&Z8()==b.key?g.ZF("yt-remote-connection-change",!0):(h9(),b9(d||null),d=Y8().oe(),(d=Z6(d,b.key))&&i9(d,1))}},aCa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},v7={"'":"\\'"},NDa={},zBa={wY:"atp",Z2:"ska",o2:"que",z1:"mus",V2:"sus",E_:"dsp"};
S6.prototype.Sn=function(){var a=new S6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var e7,a7="",i7=f7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",TBa=f7("loadCastFramework")||f7("loadCastApplicationFramework"),cDa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(l7,g.M);g.h=l7.prototype;g.h.ZJ=function(a){this.A=arguments;this.g=!1;this.Ca?this.o=(0,g.F)()+this.qd:this.Ca=g.tg(this.B,this.qd)};
g.h.stop=function(){this.Ca&&(g.ug(this.Ca),this.Ca=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();l7.ba.V.call(this)};
g.h.aK=function(){this.o?(this.Ca=g.tg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ca=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};m7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
m7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=n7.prototype;g.h.oi=null;g.h.Ef=!1;g.h.Sk=null;g.h.dw=null;g.h.Ck=null;g.h.Lj=null;g.h.mh=null;g.h.Jh=null;g.h.Ti=null;g.h.Qc=null;g.h.Tm=0;g.h.Ff=null;g.h.Gq=null;g.h.nh=null;g.h.Gl=-1;g.h.hE=!0;g.h.Yh=!1;g.h.Bs=0;g.h.Rp=null;var ZBa={},q7={};g.h=n7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.xV=function(a){a=a.target;var b=this.Rp;b&&3==g.ix(a)?b.Jj():this.zF(a)};
g.h.zF=function(a){try{if(a==this.Qc)a:{var b=g.ix(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.yd&&!g.uc(10)||g.Ad&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.df&&!g.mx(this.Qc))break a;this.Yh||4!=b||7==c||(8==c||0>=d?this.g.yf(3):this.g.yf(2));x7(this);var e=this.Qc.getStatus();this.Gl=e;var f=g.mx(this.Qc);(this.Ef=200==e)?(4==b&&t7(this),this.B?($Ba(this,b,f),g.df&&this.Ef&&3==b&&(this.W.U(this.l,"tick",this.tV),this.l.start())):s7(this,f),this.Ef&&!this.Yh&&(4==b?this.g.Dp(this):
(this.Ef=!1,p7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,r7(13)):(this.nh=0,r7(14)),t7(this),u7(this))}}catch(k){this.Qc&&g.mx(this.Qc)}finally{}};
g.h.tV=function(){var a=g.ix(this.Qc),b=g.mx(this.Qc);this.Tm<b.length&&(x7(this),$Ba(this,a,b),this.Ef&&4!=a&&p7(this))};
g.h.GU=function(a){w7((0,g.z)(this.FU,this,a),0)};
g.h.FU=function(a){this.Yh||(x7(this),s7(this,a),p7(this))};
g.h.qD=function(a){w7((0,g.z)(this.EU,this,a),0)};
g.h.EU=function(a){this.Yh||(t7(this),this.Ef=a,this.g.Dp(this),this.g.yf(4))};
g.h.cancel=function(){this.Yh=!0;t7(this)};
g.h.WU=function(){this.Sk=null;var a=(0,g.F)();0<=a-this.dw?(2!=this.Lj&&this.g.yf(3),t7(this),this.nh=2,r7(18),u7(this)):cCa(this,this.dw-a)};g.h=fCa.prototype;g.h.zs=null;g.h.we=null;g.h.Sp=!1;g.h.zz=null;g.h.ho=null;g.h.Gt=null;g.h.As=null;g.h.Ne=null;g.h.Dg=-1;g.h.Fl=null;g.h.al=null;g.h.connect=function(a){this.As=a;a=z7(this.g,null,this.As);r7(3);this.zz=(0,g.F)();var b=this.g.F;null!=b?(this.Fl=b[0],(this.al=b[1])?(this.Ne=1,gCa(this)):(this.Ne=2,B7(this))):(R6(a,"MODE","init"),this.we=new n7(this,void 0,void 0,void 0),this.we.oi=this.zs,o7(this.we,a,!1,null,!0),this.Ne=0)};
g.h.mJ=function(a){if(a)this.Ne=2,B7(this);else{r7(4);var b=this.g;b.Tf=b.ah.Dg;I7(b,9)}a&&this.yf(2)};
g.h.Mr=function(a){return this.g.Mr(a)};
g.h.abort=function(){this.we&&(this.we.cancel(),this.we=null);this.Dg=-1};
g.h.yz=function(){return!1};
g.h.jD=function(a,b){this.Dg=a.Gl;if(0==this.Ne)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Tf=this.Dg;I7(c,2);return}this.Fl=c[0];this.al=c[1]}else c=this.g,c.Tf=this.Dg,I7(c,2);else if(2==this.Ne)if(this.Sp)r7(7),this.Gt=(0,g.F)();else if("11111"==b){if(r7(6),this.Sp=!0,this.ho=(0,g.F)(),c=this.ho-this.zz,!g.yd||g.uc(10)||500>c)this.Dg=200,this.we.cancel(),r7(12),A7(this.g,this,!0)}else r7(8),this.ho=this.Gt=(0,g.F)(),this.Sp=!1};
g.h.Dp=function(){this.Dg=this.we.Gl;if(this.we.Ef)0==this.Ne?this.al?(this.Ne=1,gCa(this)):(this.Ne=2,B7(this)):2==this.Ne&&((!g.yd||g.uc(10)?!this.Sp:200>this.Gt-this.ho)?(r7(11),A7(this.g,this,!1)):(r7(12),A7(this.g,this,!0)));else{0==this.Ne?r7(9):2==this.Ne&&r7(10);var a=this.g;a.Tf=this.Dg;I7(a,2)}};
g.h.Jm=function(){return this.g.Jm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.yf=function(a){this.g.yf(a)};g.h=C7.prototype;g.h.rl=null;g.h.be=null;g.h.tc=null;g.h.ys=null;g.h.mo=null;g.h.Kx=null;g.h.zo=null;g.h.rm=0;g.h.sQ=0;g.h.pd=null;g.h.eh=null;g.h.sg=null;g.h.di=null;g.h.ah=null;g.h.Fq=null;g.h.Zj=-1;g.h.yA=-1;g.h.Tf=-1;g.h.Aj=0;g.h.nj=0;g.h.bi=8;var J7=new g.Df;g.A(iCa,g.bf);g.A(jCa,g.bf);g.A(kCa,g.bf);g.h=C7.prototype;g.h.connect=function(a,b,c,d,e){r7(0);this.ys=b;this.rl=c||{};d&&g.t(e)&&(this.rl.OSID=d,this.rl.OAID=e);this.C?(w7((0,g.z)(this.hy,this,a),100),oCa(this)):this.hy(a)};
g.h.hy=function(a){this.ah=new fCa(this);this.ah.zs=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.yz=function(){return 0==this.g};
g.h.oD=function(a){this.eh=null;rCa(this,a)};
g.h.nD=function(){this.sg=null;this.tc=new n7(this,this.o,"rpc",this.D);this.tc.oi=null;this.tc.Bs=0;var a=this.Kx.clone();g.Fm(a,"RID","rpc");g.Fm(a,"SID",this.o);g.Fm(a,"CI",this.Fq?"0":"1");g.Fm(a,"AID",this.Zj);D7(this,a);if(!g.yd||g.uc(10))g.Fm(a,"TYPE","xmlhttp"),o7(this.tc,a,!0,this.zo,!1);else{g.Fm(a,"TYPE","html");var b=this.tc,c=!!this.zo;b.Lj=3;b.mh=Q6(a.clone());bCa(b,c)}};
g.h.jD=function(a,b){if(0!=this.g&&(this.tc==a||this.be==a))if(this.Tf=a.Gl,this.be==a&&3==this.g)if(7<this.bi){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.sg){if(this.tc)if(this.tc.Ck+3E3<this.be.Ck)F7(this),this.tc.cancel(),this.tc=null;else break a;H7(this);r7(19)}}else this.yA=c[1],0<this.yA-this.Zj&&37500>c[2]&&this.Fq&&0==this.nj&&!this.di&&(this.di=w7((0,g.z)(this.VQ,this),6E3));else I7(this,11)}else b!=NDa.zZ.g&&I7(this,11);else if(this.tc==a&&
F7(this),!g.C(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Zj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.zo=e[2],e=e[3],null!=e?this.bi=e:this.bi=6,this.g=3,this.pd&&this.pd.Wx(),this.Kx=z7(this,this.Jm()?this.zo:null,this.ys),sCa(this)):"stop"==e[0]&&I7(this,7):3==this.g&&("stop"==e[0]?I7(this,7):"noop"!=e[0]&&this.pd&&this.pd.Vx(e),this.nj=0)}}};
g.h.VQ=function(){null!=this.di&&(this.di=null,this.tc.cancel(),this.tc=null,H7(this),r7(20))};
g.h.Dp=function(a){if(this.tc==a){F7(this);this.tc=null;var b=2}else if(this.be==a)this.be=null,b=1;else return;this.Tf=a.Gl;if(0!=this.g)if(a.Ef)1==b?(b=(0,g.F)()-a.Ck,J7.dispatchEvent(new jCa(J7,a.Ti?a.Ti.length:0,b,this.Aj)),E7(this),this.A.length=0):sCa(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.Tf)){if(d=1==b)this.be||this.eh||1==this.g||2<=this.Aj?d=!1:(this.eh=w7((0,g.z)(this.oD,this,a),tCa(this,this.Aj)),this.Aj++,d=!0);d=!(d||2==b&&H7(this))}if(d)switch(c){case 1:I7(this,5);
break;case 4:I7(this,10);break;case 3:I7(this,6);break;case 7:I7(this,12);break;default:I7(this,2)}}};
g.h.HJ=function(a){if(!g.Qa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.rW=function(a){a?r7(2):(r7(1),uCa(this,8))};
g.h.Mr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.cx;a.F=!1;return a};
g.h.isActive=function(){return!!this.pd&&this.pd.isActive(this)};
g.h.yf=function(a){J7.dispatchEvent(new kCa(J7,a))};
g.h.Jm=function(){return!(!g.yd||g.uc(10))};
g.h=vCa.prototype;g.h.Wx=function(){};
g.h.Vx=function(){};
g.h.Ux=function(){};
g.h.yr=function(){};
g.h.ez=function(){return{}};
g.h.isActive=function(){return!0};g.A(K7,g.M);g.h=K7.prototype;g.h.xU=function(){this.qd=Math.min(3E5,2*this.qd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.qd+15E3*Math.random();g.Zt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.qd=5E3};g.A(L7,vCa);g.h=L7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Td=function(a){return this.o.Td(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.$e(this.o),yCa(this),g.$e(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new C7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.pd=null);d.pd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Zj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):M7(this)&&pCa(this.g,c)};
g.h.Wx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)pCa(this.g,a[b])}this.R("handlerOpened")};
g.h.Ux=function(a){var b=2==a&&401==this.g.Tf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.yr=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.ez=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.fc(a,this.B);return a};
g.h.Vx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),nCa(this.g)):this.R("handlerMessage",new wCa(a[0],a[1]))};
g.h.cX=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.be&&b++;0!=b||this.connect(this.B,this.A)};N7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
N7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
N7.prototype.B=function(a){a(Error("request timed out"))};var GCa=(0,g.F)(),Q7=null,T7=Array(50),S7=-1,U7=!1;g.A(V7,g.JF);V7.prototype.oe=function(){return this.g};
V7.prototype.contains=function(a){return!!Y6(this.g,a)};
V7.prototype.get=function(a){return a?Z6(this.g,a):null};
V7.prototype.info=function(a){R7(this.D,a)};g.A(W7,g.JF);var ODa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=W7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ca)&&this.EF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ca)||(g.$D(this.Ca),this.Ca=window.NaN)};
g.h.V=function(){this.stop();W7.ba.V.call(this)};
g.h.EF=function(){this.Ca=window.NaN;this.g=g.oE(O7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.eX,this),onError:(0,g.z)(this.dX,this),wd:(0,g.z)(this.fX,this)})};
g.h.eX=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new T6(c))};
g.h.dX=function(a){this.g=null;a.status&&404==a.status?this.l>=ODa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=ODa[this.l],this.Ca=g.YD((0,g.z)(this.EF,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.fX=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(Y7,V7);g.h=Y7.prototype;g.h.start=function(){X7(this)&&this.R("screenChange");!g.TG("yt-remote-lounge-token-expiration")&&KCa(this);g.$D(this.l);this.l=g.YD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){X7(this);HCa(this,a);Z7(this,!1);this.R("screenChange");b(a);a.token||KCa(this)};
g.h.remove=function(a,b){var c=X7(this);JCa(this,a)&&(Z7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.zq=function(a,b,c,d){var e=X7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,Z7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.$D(this.l);Y7.ba.V.call(this)};
g.h.nK=function(a){X7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}Z7(this,!b);b&&R7(this.D,"Missed "+b+" lounge tokens.")};
g.h.mK=function(a){R7(this.D,"Requesting lounge tokens failed: "+a)};g.A(a8,g.JF);g.h=a8.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.TG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?c8(this):(this.A=(0,g.F)()+3E5,g.SG("yt-remote-fast-check-period",this.A),this.tv())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){$7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.g,function(b,d){return b&&!!Z6(a,d)},this);
b8(this,b)};
g.h.V=function(){g.$D(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);a8.ba.V.call(this)};
g.h.tv=function(){g.$D(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=NCa(this);if(g.Pb(a)){var b=O7(this.B,"/pairing/get_screen_availability");this.l=P7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.z)(this.eU,this,a),(0,g.z)(this.dU,this))}else b8(this,{}),c8(this)};
g.h.eU=function(a,b){this.l=null;var c=g.Sb(NCa(this));if(g.jb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;b8(this,d);c8(this)}else this.fc("Changing Screen set during request."),this.tv()};
g.h.dU=function(a){this.fc("Screen availability failed: "+a);this.l=null;c8(this)};
g.h.fc=function(a){R7("OnlineScreenService",a)};g.A(d8,V7);g.h=d8.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.zq=function(a,b,c,d){this.o.contains(a)?this.o.zq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,R7(this.D,a),d(Error(a)))};
g.h.oe=function(a){return a?this.g:g.Xa(this.g,(0,g.Ld)(this.A,function(a){return!this.contains(a)},this))};
g.h.FF=function(){return(0,g.Ld)(this.oe(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.GF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new W7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.$e(f);d(e8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.$e(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.hX=function(a,b,c,d){g.oE(O7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new T6(d.screen||{});if(!e.name||RCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);RCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(e8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.$e(this.o);g.$e(this.l);d8.ba.V.call(this)};
g.h.CK=function(){SCa(this);this.R("screenChange");this.l.update()};
d8.prototype.dispose=d8.prototype.dispose;g.A(g8,g.JF);g.h=g8.prototype;g.h.Ep=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.te=function(a){this.ka()||(a&&h8(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){R7(this.K,a)};
g.h.IF=function(){return null};
g.h.Av=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){h8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Av("");g8.ba.V.call(this)};g.A(i8,g8);g.h=i8.prototype;g.h.zv=function(a){if(this.g){if(this.g==a)return;h8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);UCa(this)};
g.h.bk=function(a){this.info("launchWithParams no-op for Cast: "+g.zg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.te()},this),(0,g.z)(function(){this.te(Error("Failed to stop receiver app."))},this)):this.te(Error("Stopping cast device witout session."))};
g.h.Av=g.y;g.h.V=function(){this.info("disposeInternal");g.$D(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;i8.ba.V.call(this)};
g.h.iV=function(a,b){if(!this.ka())if(b){var c=g.Xw(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.zg(c));switch(d){case "mdxSessionStatus":TCa(this,c.screenId);break;default:h8(this,"Unknown youtube message: "+d)}}else h8(this,"Unable to parse message.")}else h8(this,"No data in message.")};
g.h.oz=function(a,b,c,d){QCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(h8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.YD((0,g.z)(this.oz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.IF=function(){return this.g};
g.h.iX=function(a){this.ka()||a||(h8(this,"Cast session died."),this.te())};g.A(j8,g8);g.h=j8.prototype;g.h.zv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.bk=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.$D(this.C);this.A?this.A.stop((0,g.z)(this.te,this,null),(0,g.z)(this.te,this,"Failed to stop DIAL device.")):this.te()};
g.h.V=function(){this.g();this.g=g.y;g.$D(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;j8.ba.V.call(this)};
g.h.lX=function(a){this.ka()||a||(h8(this,"DIAL session died."),this.g(),this.g=g.y,this.te())};
g.h.qt=function(a){this.I=X6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,WCa(this));a(b);VCa(this)}else this.D=(0,g.z)(function(){g.$D(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,WCa(this));a(b);VCa(this)},this),this.C=g.YD((0,g.z)(function(){this.D()},this),100)};
g.h.RL=function(a,b,c){QCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Ep(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.qt(b,c)},this),(0,g.z)(function(a){h8(this,"Failed to get DIAL screen: "+a);
this.qt(b,c)},this))};g.A(k8,g8);k8.prototype.stop=function(){this.te()};
k8.prototype.zv=g.y;k8.prototype.bk=function(){g.$D(this.g);this.g=window.NaN;var a=Z6(this.H.oe(),this.l.label);a?this.Ep(a):this.te(Error("No such screen"))};
k8.prototype.V=function(){g.$D(this.g);this.g=window.NaN;k8.ba.V.call(this)};g.A(l8,g.JF);g.h=l8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.kD,this),(0,g.z)(this.KT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.GR,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),DCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.HF,this)),this.o=YCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.zg(a))},this)),this.R("yt-remote-cast2-availability-change",n8(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.zg(a));
b(!1)},this))};
g.h.ZV=function(a,b){m8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)m8("Unsetting old screen status: "+this.g.l.friendlyName),o8(this,null)}if(a&&b){if(!this.g){c=Z6(this.l.oe(),a);if(!c){m8("setConnectedScreenStatus: Unknown screen.");return}var d=XCa(this,c);d||(m8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.zg(a))},this)));
m8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);o8(this,new k8(this.l,d),!0)}this.g.Av(b)}else m8("setConnectedScreenStatus: no screen.")};
g.h.aW=function(a){this.ka()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.bk(a):this.fc("Setting connection data without a session")};
g.h.kX=function(){this.ka()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),o8(this,null)):m8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.kD,this),(0,g.z)(this.jU,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.HF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Va(g.x("yt.mdx.remote.debug.handlers_")||[],ACa);g.$e(this.g);l8.ba.V.call(this)};
g.h.fc=function(a){R7("Controller",a)};
g.h.lD=function(a,b){this.g==a&&(b||o8(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.GT=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),m8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)m8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{m8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:o8(this,
new k8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:o8(this,new j8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:o8(this,new i8(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.GR=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return m8("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);o8(this,new j8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.RL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.qt,b))};
g.h.kD=function(a){if(!this.ka()){m8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)m8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),o8(this,new i8(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=Z6(this.l.oe(),c.label);
d&&U6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(m8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.$e(this.g),this.g=new i8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.lD,this,this.g)),this.g.bk(null));this.g.zv(a)}}};
g.h.jX=function(){return this.g?this.g.IF():null};
g.h.jU=function(a){this.ka()||(this.fc("Failed to estabilish a session: "+g.zg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&o8(this,null))};
g.h.KT=function(a){m8("Receiver availability updated: "+a);if(!this.ka()){var b=n8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;n8(this)!=b&&this.R("yt-remote-cast2-availability-change",n8(this))}};
g.h.HF=function(){this.ka()||(this.o=YCa(this),m8("Updating custom receivers: "+g.zg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",n8(this)))};
l8.prototype.setLaunchParams=l8.prototype.aW;l8.prototype.setConnectedScreenStatus=l8.prototype.ZV;l8.prototype.stopSession=l8.prototype.kX;l8.prototype.getCastSession=l8.prototype.jX;l8.prototype.requestSession=l8.prototype.requestSession;l8.prototype.init=l8.prototype.init;l8.prototype.dispose=l8.prototype.dispose;var u8=[];g.h=z8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";A8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Wf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.ob=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+B8(this):this.H};
g.h.clone=function(){return new z8(F8(this))};g.A(H8,g.JF);g.h=H8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,N8(this,"play")):M8(this,"play"),L8(this,1,D8(I8(this))),this.R("remotePlayerChange")):J8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,N8(this,"pause")):M8(this,"pause"),L8(this,2,D8(I8(this))),this.R("remotePlayerChange")):J8(this,this.pause)};
g.h.DF=function(a){if(1==this.g){if(this.l){var b=I8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,N8(this,"seekTo",{newTime:a}))}else M8(this,"seekTo",{newTime:a});L8(this,3,a);this.R("remotePlayerChange")}else J8(this,g.Ga(this.DF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,N8(this,"stopVideo")):M8(this,"stopVideo");var a=I8(this);a.index=-1;a.videoId="";A8(a);K8(this,a);this.R("remotePlayerChange")}else J8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=I8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){R7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){R7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);M8(this,"setVolume",e)}c.muted=b;c.volume=a;K8(this,c)}else J8(this,g.Ga(this.setVolume,a,b))};
g.h.CE=function(a,b){if(1==this.g){var c=I8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.zg(b.style),g.fc(d,c.l));M8(this,"setSubtitlesTrack",d);K8(this,c)}else J8(this,g.Ga(this.CE,a,b))};
g.h.kw=function(a,b){if(1==this.g){M8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Hb.id});var c=I8(this);c.audioTrackId=b.Hb.id;K8(this,c)}else J8(this,g.Ga(this.kw,a,b))};
g.h.CF=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"previous")}else J8(this,g.Ga(this.CF,a,b))};
g.h.BF=function(a,b){if(1==this.g){if(a&&b){var c=I8(this);E8(c,a,b);K8(this,c)}M8(this,"next")}else J8(this,g.Ga(this.BF,a,b))};
g.h.Ey=function(){1==this.g?M8(this,"dismissAutoplay"):J8(this,this.Ey)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}H8.ba.dispose.call(this)};
g.h.V=function(){kDa(this);this.A=null;this.B.clear();G8(this,null);H8.ba.V.call(this)};
g.h.lw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.rC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.BT=function(a,b){this.R(a,b)};
g.h.cR=function(a){if(!a)this.wm(null),G8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=I8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)R7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,K8(this,b)}};
g.h.wm=function(a){R7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),lDa(this),this.R("remotePlayerChange")};
g.h.bR=function(a){a?(lDa(this),this.R("remotePlayerChange")):this.wm(null)};
g.h.oR=function(){var a=hDa();a&&G8(this,a)};
g.h.fc=function(a){R7("CP",a)};g.A(O8,g.JF);g.h=O8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;C8(this.Za,m);this.A="UNSUPPORTED";P8("Connecting with setPlaylist and params: "+g.zg(l));this.g.connect({method:"setPlaylist",
params:g.zg(l)},a,HBa())}else P8("Connecting without params"),this.g.connect({},a,HBa());nDa(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),Q8(this,3));O8.ba.dispose.call(this)};
g.h.V=function(){R8(this);T8(this);S8(this);g.$D(this.H);this.H=window.NaN;g.$D(this.I);this.I=window.NaN;this.o=null;g.tF(this.T);this.T.length=0;this.g.dispose();O8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.eK=function(){this.C(2)};
g.h.gR=function(){P8("Channel opened");this.M&&(this.M=!1,S8(this),this.K=g.YD((0,g.z)(function(){P8("Timing out waiting for a screen.");this.C(1)},this),15E3));
LBa(xCa(this.g),this.Z)};
g.h.dR=function(){P8("Channel closed");(0,window.isNaN)(this.B)?d7(!0):d7();this.dispose()};
g.h.eR=function(a){d7();(0,window.isNaN)(this.F())?(P8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,P8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Q8(this,2))};
g.h.fR=function(a){a.params?P8("Received: action="+a.action+", params="+g.zg(a.params)):P8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.G)(a,function(a){return new S6(a)});
a=!!g.Ma(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
qDa(this,a);break;case "loungeScreenDisconnected":g.Wa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
qDa(this,!1);break;case "remoteConnected":var b=new S6(g.Xw(a.params.device));g.Ma(this.l,function(a){return b?a.id==b.id:!1})||g.Ta(this.l,b);
break;case "remoteDisconnected":b=new S6(g.Xw(a.params.device));g.Wa(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":sDa(this,a);break;case "nowPlaying":uDa(this,a);break;case "onStateChange":tDa(this,a);break;case "onAdStateChange":vDa(this,a);break;case "onVolumeChanged":wDa(this,a);break;case "onSubtitlesTrackChanged":rDa(this,a);break;case "nowAutoplaying":xDa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":yDa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:P8("Unrecognized action: "+a.action)}};
g.h.JV=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&U8(this,"getNowPlaying")}};
O8.prototype.subscribe=O8.prototype.subscribe;O8.prototype.unsubscribeByKey=O8.prototype.Td;O8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?M7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
O8.prototype.getProxyState=O8.prototype.ga;O8.prototype.C=function(a){P8("Disconnecting with "+a);R8(this);this.R("beforeDisconnect",a);1==a&&d7();yCa(this.g,a);this.dispose()};
O8.prototype.disconnect=O8.prototype.C;O8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),E8(a,this.o,a.index));return F8(a)};
O8.prototype.getPlayerContextData=O8.prototype.fa;
O8.prototype.oa=function(a){var b=new z8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.$D(this.H),this.H=g.YD((0,g.z)(this.JV,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&D8(this.Za)==D8(b)&&g.zg(this.Za.l)==g.zg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
O8.prototype.setPlayerContextData=O8.prototype.oa;O8.prototype.X=function(){var a=this.g.C.id,b=g.Ma(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
O8.prototype.getOtherConnectedRemoteId=O8.prototype.X;O8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
O8.prototype.getReconnectTimeout=O8.prototype.F;O8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
O8.prototype.getAutoplayMode=O8.prototype.Y;O8.prototype.ca=function(){return this.D||""};
O8.prototype.getAutoplayVideoId=O8.prototype.ca;O8.prototype.ua=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.$t(a.g);a.start()}};
O8.prototype.reconnect=O8.prototype.ua;O8.prototype.ha=function(a,b){U8(this,a,b);pDa(this)};
O8.prototype.sendMessage=O8.prototype.ha;g.A(V8,V7);g.h=V8.prototype;g.h.oe=function(a){return this.gd.$_gs(a)};
g.h.contains=function(a){return!!this.gd.$_c(a)};
g.h.get=function(a){return this.gd.$_g(a)};
g.h.start=function(){this.gd.$_st()};
g.h.add=function(a,b,c){this.gd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.gd.$_r(a,b,c)};
g.h.zq=function(a,b,c,d){this.gd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.gd.$_ubk(this.l[a]);this.l.length=0;this.gd=null;V8.ba.V.call(this)};
g.h.gX=function(){this.R("screenChange")};
g.h.dT=function(){this.R("onlineScreenChange")};
d8.prototype.$_st=d8.prototype.start;d8.prototype.$_gspc=d8.prototype.hX;d8.prototype.$_gsppc=d8.prototype.GF;d8.prototype.$_c=d8.prototype.contains;d8.prototype.$_g=d8.prototype.get;d8.prototype.$_a=d8.prototype.add;d8.prototype.$_un=d8.prototype.zq;d8.prototype.$_r=d8.prototype.remove;d8.prototype.$_gs=d8.prototype.oe;d8.prototype.$_gos=d8.prototype.FF;d8.prototype.$_s=d8.prototype.subscribe;d8.prototype.$_ubk=d8.prototype.Td;var W8=null,X8=null,l9=null,a9=[];g.q(m9,g.M);g.h=m9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.iD,this);this.g.unsubscribe("remotePlayerChange",this.zm,this);this.g.unsubscribe("remoteQueueChange",this.Fp,this);this.g.unsubscribe("autoplayUpNext",this.GC,this);this.g.unsubscribe("previousNextChange",this.fD,this);this.g.unsubscribe("nowAutoplaying",this.XC,this);this.g.unsubscribe("autoplayDismissed",this.FC,this);this.g=this.F=null};
g.h.GB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(!I8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":I8(this.g).ob()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Jj(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.kw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();r9(this,0==c?void 0:c);break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.kw(this.l.getVideoData(1).videoId,c)}};
g.h.aR=function(a){this.J.ZJ(a)};
g.h.HW=function(a){this.GB("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.TE=function(){var a=this.l.xc("captions","track");g.Yb(a)||q9(this,a)};
g.h.VC=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.zm,this);var b=Math.round(a.volume);a=!!a.muted;var c=I8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.zm,this)}};
g.h.vS=function(){g.Yb(this.C)||KDa(this,this.C);this.D=!1};
g.h.iD=function(a,b){this.B.stop();2==b&&this.QE()};
g.h.zm=function(){if(p9(this)){this.A.stop();var a=I8(this.g);switch(a.g){case 1081:case 1:o9(this,new g.vP(8));this.PE();break;case 1085:case 3:o9(this,new g.vP(9));break;case 1083:case 0:o9(this,new g.vP(2));this.I.stop();n9(this,this.l.getVideoData().lengthSeconds);break;case 1084:o9(this,new g.vP(4));break;case 2:o9(this,new g.vP(4));n9(this,D8(a));break;case -1:o9(this,new g.vP(64));break;case -1E3:o9(this,new g.vP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
I8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,KDa(this,a));a=I8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.pF()}else JDa(this)};
g.h.fD=function(){this.l.R("mdxpreviousnextchange")};
g.h.Fp=function(){p9(this)||JDa(this)};
g.h.lJ=function(){this.g.Ey()};
g.h.GC=function(a){a&&(a=g.oE("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.JU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.JU=function(a,b){var c=new g.oO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.XC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.FC=function(){this.l.R("mdxautoplaycanceled")};
g.h.ZO=function(a,b){-1==I8(this.g).g?r9(this,a):b&&this.g.DF(a)};
g.h.pF=function(){if(p9(this)){var a=I8(this.g);this.o.Ea(this.T);a.muted?this.l.mute():this.l.fg();this.l.setVolume(a.volume);this.T=this.o.O(this.l,"onVolumeChange",this.VC)}};
g.h.PE=function(){this.A.stop();if(!this.g.ka()){var a=I8(this.g);a.ob()&&o9(this,new g.vP(8));n9(this,D8(a));this.A.start()}};
g.h.QE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.q(s9,g.W);s9.prototype.B=function(a){MDa(this,a.state)};g.q(t9,g.SZ);t9.prototype.J=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.H=g.lb(a,this.C,this),g.TZ(this,(0,g.G)(a,this.C)),a=this.l.xc("remote","currentReceiver"),this.xf(this.C(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.C=function(a){return a.key};
t9.prototype.wf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
t9.prototype.td=function(a){g.SZ.prototype.td.call(this,a);this.l.Od("remote","currentReceiver",this.H[a]);this.B.Qb()};g.q(u9,g.oV);g.h=u9.prototype;g.h.create=function(){DDa(g.DM(g.Y(this.g)));this.C.push(g.VF("yt-remote-before-disconnect",this.WQ,this));this.C.push(g.VF("yt-remote-connection-change",this.LT,this));this.C.push(g.VF("yt-remote-receiver-availability-change",this.gD,this));this.C.push(g.VF("yt-remote-auto-connect",this.JT,this));this.C.push(g.VF("yt-remote-receiver-resumed",this.IT,this));this.gD()};
g.h.load=function(){this.g.mu();g.oV.prototype.load.call(this);this.B=new m9(this,this.g,this.l);var a=(a=IDa())?a.currentTime:0;var b=k9()?new H8(f9(),void 0):null;0==a&&b&&(a=D8(I8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));LDa(this,this.D,this.D);g.p0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.af(this.B,this.l);this.l=this.B=null;g.oV.prototype.unload.call(this);g.p0(this.g.app,5)};
g.h.V=function(){g.WF(this.C);g.oV.prototype.V.call(this)};
g.h.jm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.GB.apply(this.B,[a].concat(g.pa(c)))};
g.h.VJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Wf=function(){return this.l?I8(this.l).Wf:!1};
g.h.hasNext=function(){return this.l?I8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.NO=function(){var a=I8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+B8(a):a.A,isPeggedToLive:1>=(a.C?a.o+B8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+B8(a):a.o,seekableStart:0<a.B?a.B+B8(a):a.B}};
g.h.OO=function(){this.l&&this.l.BF()};
g.h.PO=function(){this.l&&this.l.CF()};
g.h.WQ=function(a){1==a&&(this.I=this.l?I8(this.l):null)};
g.h.LT=function(){var a=k9()?new H8(f9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.$e(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.kB(a.videoId,D8(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.gD=function(){this.F=[this.o].concat(FDa());var a=g9()||this.o;v9(this,a);this.g.va("onMdxReceiversChange")};
g.h.JT=function(){var a=g9();v9(this,a)};
g.h.IT=function(){this.A=g9()};
g.h.MO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?x8():v9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&x8(),!0):!1}};
g.h.QO=function(){M8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ac=function(){return!1};g.fY.remote=u9;})(_yt_player);
